function []=dataCallback(source,cbdata,mAxes,mPlots,mControls,mParams)

% Save/load subject analysis results
addpath('.\export_fig')
actionName = source.String;
eventTag = source.Parent.Tag;

subjectIndex = getappdata(mPlots.Result.Parent,'subjectIndex');
validEventNum = getappdata(mPlots.Result.Parent,'validEventNum');
% The following features are saved to a local file so that the next time it
% is loaded, all the states/progress are restored.
fieldNamesAnalysis = {...
    'BPMaxLoc','BPMax','BPMinLoc','BPMin','ECGMaxLoc','ECGMax',...
    'BCGScaleHWaveLoc','BCGScaleHWave','BCGScaleIWaveLoc','BCGScaleIWave','BCGScaleJWaveLoc','BCGScaleJWave','BCGScaleKWaveLoc','BCGScaleKWave','BCGScaleLWaveLoc','BCGScaleLWave',...
    'BCGWristHWaveLoc','BCGWristHWave','BCGWristIWaveLoc','BCGWristIWave','BCGWristJWaveLoc','BCGWristJWave','BCGWristKWaveLoc','BCGWristKWave','BCGWristLWaveLoc','BCGWristLWave',...
    'BCGArmHWaveLoc','BCGArmHWave','BCGArmIWaveLoc','BCGArmIWave','BCGArmJWaveLoc','BCGArmJWave','BCGArmKWaveLoc','BCGArmKWave','BCGArmLWaveLoc','BCGArmLWave',...
    'BCGNeckHWaveLoc','BCGNeckHWave','BCGNeckIWaveLoc','BCGNeckIWave','BCGNeckJWaveLoc','BCGNeckJWave','BCGNeckKWaveLoc','BCGNeckKWave','BCGNeckLWaveLoc','BCGNeckLWave',...
    'PPGClipMaxLoc','PPGClipMax','PPGClipMinLoc','PPGClipMin','PPGClipFoot','PPGClipFootLoc',...
    'PPGIRMaxLoc','PPGIRMax','PPGIRMinLoc','PPGIRMin','PPGIRFoot','PPGIRFootLoc',... 
    'PPGGreenMaxLoc','PPGGreenMax','PPGGreenMinLoc','PPGGreenMin','PPGGreenFoot','PPGGreenFootLoc',...
    ...
    'DPPPGClipBCGScaleWindow','DPPPGClipBCGWristWindow','DPPPGClipBCGArmWindow','DPPPGClipBCGNeckWindow',...
    'DPPPGIRBCGScaleWindow','DPPPGIRBCGWristWindow','DPPPGIRBCGArmWindow','DPPPGIRBCGNeckWindow',...
    'DPPPGGreenBCGScaleWindow','DPPPGGreenBCGWristWindow','DPPPGGreenBCGArmWindow','DPPPGGreenBCGNeckWindow',...
    'PPPPGClipBCGScaleWindow','PPPPGClipBCGWristWindow','PPPPGClipBCGArmWindow','PPPPGClipBCGNeckWindow',...
    'PPPPGIRBCGScaleWindow','PPPPGIRBCGWristWindow','PPPPGIRBCGArmWindow','PPPPGIRBCGNeckWindow',...
    'PPPPGGreenBCGScaleWindow','PPPPGGreenBCGWristWindow','PPPPGGreenBCGArmWindow','PPPPGGreenBCGNeckWindow',...
    ...
    'DPPPGClipBCGScaleBPInfo','DPPPGClipBCGWristBPInfo','DPPPGClipBCGArmBPInfo','DPPPGClipBCGNeckBPInfo',...
    'DPPPGIRBCGScaleBPInfo','DPPPGIRBCGWristBPInfo','DPPPGIRBCGArmBPInfo','DPPPGIRBCGNeckBPInfo',...
    'DPPPGGreenBCGScaleBPInfo','DPPPGGreenBCGWristBPInfo','DPPPGGreenBCGArmBPInfo','DPPPGGreenBCGNeckBPInfo',...
    'PPPPGClipBCGScaleBPInfo','PPPPGClipBCGWristBPInfo','PPPPGClipBCGArmBPInfo','PPPPGClipBCGNeckBPInfo',...
    'PPPPGIRBCGScaleBPInfo','PPPPGIRBCGWristBPInfo','PPPPGIRBCGArmBPInfo','PPPPGIRBCGNeckBPInfo',...
    'PPPPGGreenBCGScaleBPInfo','PPPPGGreenBCGWristBPInfo','PPPPGGreenBCGArmBPInfo','PPPPGGreenBCGNeckBPInfo',...
    ...
    'IJDPBCGScaleIntervalWindow','IJDPBCGWristIntervalWindow','IJDPBCGArmIntervalWindow','IJDPBCGNeckIntervalWindow',...
    'IJDPBCGScaleAmplitudeWindow','IJDPBCGWristAmplitudeWindow','IJDPBCGArmAmplitudeWindow','IJDPBCGNeckAmplitudeWindow',...
    'IJPPBCGScaleIntervalWindow','IJPPBCGWristIntervalWindow','IJPPBCGArmIntervalWindow','IJPPBCGNeckIntervalWindow',...
    'IJPPBCGScaleAmplitudeWindow','IJPPBCGWristAmplitudeWindow','IJPPBCGArmAmplitudeWindow','IJPPBCGNeckAmplitudeWindow',...
    ...
    'JKDPBCGScaleIntervalWindow','JKDPBCGWristIntervalWindow','JKDPBCGArmIntervalWindow','JKDPBCGNeckIntervalWindow',...
    'JKDPBCGScaleAmplitudeWindow','JKDPBCGWristAmplitudeWindow','JKDPBCGArmAmplitudeWindow','JKDPBCGNeckAmplitudeWindow',...
    'JKPPBCGScaleIntervalWindow','JKPPBCGWristIntervalWindow','JKPPBCGArmIntervalWindow','JKPPBCGNeckIntervalWindow',...
    'JKPPBCGScaleAmplitudeWindow','JKPPBCGWristAmplitudeWindow','JKPPBCGArmAmplitudeWindow','JKPPBCGNeckAmplitudeWindow',...
    ...
    'IKDPBCGScaleIntervalWindow','IKDPBCGWristIntervalWindow','IKDPBCGArmIntervalWindow','IKDPBCGNeckIntervalWindow',...
    'IKDPBCGScaleAmplitudeWindow','IKDPBCGWristAmplitudeWindow','IKDPBCGArmAmplitudeWindow','IKDPBCGNeckAmplitudeWindow',...
    'IKPPBCGScaleIntervalWindow','IKPPBCGWristIntervalWindow','IKPPBCGArmIntervalWindow','IKPPBCGNeckIntervalWindow',...
    'IKPPBCGScaleAmplitudeWindow','IKPPBCGWristAmplitudeWindow','IKPPBCGArmAmplitudeWindow','IKPPBCGNeckAmplitudeWindow',...
    ...
    'IJDPBCGScaleIntervalBPInfo','IJDPBCGWristIntervalBPInfo','IJDPBCGArmIntervalBPInfo','IJDPBCGNeckIntervalBPInfo',...
    'IJDPBCGScaleAmplitudeBPInfo','IJDPBCGWristAmplitudeBPInfo','IJDPBCGArmAmplitudeBPInfo','IJDPBCGNeckAmplitudeBPInfo',...
    'IJPPBCGScaleIntervalBPInfo','IJPPBCGWristIntervalBPInfo','IJPPBCGArmIntervalBPInfo','IJPPBCGNeckIntervalBPInfo',...
    'IJPPBCGScaleAmplitudeBPInfo','IJPPBCGWristAmplitudeBPInfo','IJPPBCGArmAmplitudeBPInfo','IJPPBCGNeckAmplitudeBPInfo',...
    ...
    'JKDPBCGScaleIntervalBPInfo','JKDPBCGWristIntervalBPInfo','JKDPBCGArmIntervalBPInfo','JKDPBCGNeckIntervalBPInfo',...
    'JKDPBCGScaleAmplitudeBPInfo','JKDPBCGWristAmplitudeBPInfo','JKDPBCGArmAmplitudeBPInfo','JKDPBCGNeckAmplitudeBPInfo',...
    'JKPPBCGScaleIntervalBPInfo','JKPPBCGWristIntervalBPInfo','JKPPBCGArmIntervalBPInfo','JKPPBCGNeckIntervalBPInfo',...
    'JKPPBCGScaleAmplitudeBPInfo','JKPPBCGWristAmplitudeBPInfo','JKPPBCGArmAmplitudeBPInfo','JKPPBCGNeckAmplitudeBPInfo',...
    ...
    'IKDPBCGScaleIntervalBPInfo','IKDPBCGWristIntervalBPInfo','IKDPBCGArmIntervalBPInfo','IKDPBCGNeckIntervalBPInfo',...
    'IKDPBCGScaleAmplitudeBPInfo','IKDPBCGWristAmplitudeBPInfo','IKDPBCGArmAmplitudeBPInfo','IKDPBCGNeckAmplitudeBPInfo',...
    'IKPPBCGScaleIntervalBPInfo','IKPPBCGWristIntervalBPInfo','IKPPBCGArmIntervalBPInfo','IKPPBCGNeckIntervalBPInfo',...
    'IKPPBCGScaleAmplitudeBPInfo','IKPPBCGWristAmplitudeBPInfo','IKPPBCGArmAmplitudeBPInfo','IKPPBCGNeckAmplitudeBPInfo',...
    'startIdx'};

fieldNamesResult = {'PAT','PTT','SIGS','eventList','validEventNum','subjectIndex'};


if strcmp(actionName,'Load Data') == 1
    uiopen('load')
    for ii = 1:validEventNum
        for jj = 1:length(fieldNamesAnalysis)
            fieldNameAnalysis = fieldNamesAnalysis{jj};
            setappdata(mPlots.Analysis.(['Event',num2str(ii)]).Parent,fieldNameAnalysis,mResults.Analysis.(['Event',num2str(ii)]).(fieldNameAnalysis))
        end
        expMA('BCGScale',['Event',num2str(ii)],mPlots)
        expMA('BCGArm',['Event',num2str(ii)],mPlots)
    end
    for ii = 1:length(fieldNamesResult)
        fieldNameResult = fieldNamesResult{ii};
        setappdata(mPlots.Result.Parent,fieldNameResult,mResults.Result.(fieldNameResult))
    end
    scrollbarCallback(mControls.Analysis.(eventTag).hScrollSlider,[],mAxes,mPlots,mControls,mParams)
    entryCode = 0; skipCalculation = 1;
    setappdata(mPlots.Analysis.(eventTag).Parent,'entryCode',entryCode)
    setappdata(mPlots.Result.Parent,'skipCalculation',skipCalculation)
    analyze(entryCode,eventTag,mAxes,mPlots,mControls,mParams)
elseif strcmp(actionName,'Save Data') == 1
    for ii = 1:validEventNum
        for jj = 1:length(fieldNamesAnalysis)
            fieldNameAnalysis = fieldNamesAnalysis{jj};
            mResults.Analysis.(['Event',num2str(ii)]).(fieldNameAnalysis) = getappdata(mPlots.Analysis.(['Event',num2str(ii)]).Parent,fieldNameAnalysis);
        end
    end
    for ii = 1:length(fieldNamesResult)
        fieldNameResult = fieldNamesResult{ii};
        mResults.Result.(fieldNameResult) = getappdata(mPlots.Result.Parent,fieldNameResult);
    end
    save(['.\Result\Subject' num2str(subjectIndex) 'Data.mat'],'mResults')
    mPlots.Result.Tabs.SelectedTab = mPlots.Result.DP.Parent;
    export_fig(['.\Result\Subject' num2str(subjectIndex) 'DPTotal.png'],mPlots.Result.Parent)
    mPlots.Result.Tabs.SelectedTab = mPlots.Result.PP.Parent;
    export_fig(['.\Result\Subject' num2str(subjectIndex) 'PPTotal.png'],mPlots.Result.Parent)
    fprintf(['Data Saved for Subject ' num2str(subjectIndex) ' from ' eventTag '!\n'])
%     PPGfingersig = getappdata(mPlots.Analysis.Event6.Parent,'PPGfingersig');
%     startIdx = getappdata(mPlots.Analysis.Event6.Parent,'startIdx');
%     timesig = getappdata(mPlots.Analysis.Event6.Parent,'timesig');
%     save('temp.mat','PPGfingersig','startIdx','timesig')
end