function []=dataCallback(source,cbdata,mAxes,mPlots,mControls,mParams)

% Save/load subject analysis results
addpath('.\export_fig')
actionName = source.String;
eventTag = source.Parent.Tag;

subjectIndex = getappdata(mPlots.Result.Parent,'subjectIndex');
validEventNum = getappdata(mPlots.Result.Parent,'validEventNum');
% The following features are saved to a local file so that the next time it
% is loaded, all the states/progress are restored.
fieldNamesAnalysis = {...
    'BPMaxLoc','BPMax','BPMinLoc','BPMin','ECGMaxLoc','ECGMax','ICGdzdtMaxLoc','ICGdzdtMax','ICGdzdtBPoint','ICGdzdtBPointLoc',...
    'BCGMaxLoc','BCGMax','BCGMinLoc','BCGMin','PPGfingerMaxLoc','PPGfingerMax','PPGfingerMinLoc','PPGfingerMin','PPGfingerFoot','PPGfingerFootLoc',...
    'PPGearMaxLoc','PPGearMax','PPGearMinLoc','PPGearMin','PPGearFoot','PPGearFootLoc',... 
    'PPGfeetMaxLoc','PPGfeetMax','PPGfeetMinLoc','PPGfeetMin','PPGfeetFoot','PPGfeetFootLoc',...
    'PPGtoeMaxLoc','PPGtoeMax','PPGtoeMinLoc','PPGtoeMin','PPGtoeFoot','PPGtoeFootLoc',...
    'PPGfingerECGWindow','PPGearECGWindow','PPGtoeECGWindow','PPGfeetECGWindow',...
    'PPGfingerICGWindow','PPGearICGWindow','PPGtoeICGWindow','PPGfeetICGWindow',...
    'PPGfingerBCGWindow','PPGearBCGWindow','PPGtoeBCGWindow','PPGfeetBCGWindow',...
    'PPGfingerECGBPInfo','PPGearECGBPInfo','PPGtoeECGBPInfo','PPGfeetECGBPInfo',...
    'PPGfingerICGBPInfo','PPGearICGBPInfo','PPGtoeICGBPInfo','PPGfeetICGBPInfo',...
    'PPGfingerBCGBPInfo','PPGearBCGBPInfo','PPGtoeBCGBPInfo','PPGfeetBCGBPInfo',...
    'IJWindow','IJBPInfo','startIdx'};
fieldNamesAnalysisLoad = {...
    'BPMaxLoc','BPMax','BPMinLoc','BPMin','ECGMaxLoc','ECGMax','ICGdzdtMaxLoc','ICGdzdtMax','ICGdzdtBPoint','ICGdzdtBPointLoc',...
    'BCGMaxLoc','BCGMax','BCGMinLoc','BCGMin','PPGfingerMaxLoc','PPGfingerMax','PPGfingerMinLoc','PPGfingerMin','PPGfingerFoot','PPGfingerFootLoc',...
    'PPGearMaxLoc','PPGearMax','PPGearMinLoc','PPGearMin','PPGearFoot','PPGearFootLoc',... 
    'PPGfeetMaxLoc','PPGfeetMax','PPGfeetMinLoc','PPGfeetMin','PPGfeetFoot','PPGfeetFootLoc',...
    'PPGtoeMaxLoc','PPGtoeMax','PPGtoeMinLoc','PPGtoeMin','PPGtoeFoot','PPGtoeFootLoc',...
    'PPGfingerECGWindow','PPGearECGWindow','PPGtoeECGWindow','PPGfeetECGWindow',...
    'PPGfingerICGWindow','PPGearICGWindow','PPGtoeICGWindow','PPGfeetICGWindow',...
    'PPGfingerBCGWindow','PPGearBCGWindow','PPGtoeBCGWindow','PPGfeetBCGWindow',...
    'PPGfingerECGBPInfo','PPGearECGBPInfo','PPGtoeECGBPInfo','PPGfeetECGBPInfo',...
    'PPGfingerICGBPInfo','PPGearICGBPInfo','PPGtoeICGBPInfo','PPGfeetICGBPInfo',...
    'PPGfingerBCGBPInfo','PPGearBCGBPInfo','PPGtoeBCGBPInfo','PPGfeetBCGBPInfo',...
    'IJWindow','IJBPInfo'};

fieldNamesResult = {'PAT','PTT','IJInfo','eventList','validEventNum','subjectIndex'};


if strcmp(actionName,'Load Data') == 1
    uiopen('load')
    for ii = 1:validEventNum
        for jj = 1:length(fieldNamesAnalysisLoad)
            fieldNameAnalysis = fieldNamesAnalysisLoad{jj};
            setappdata(mPlots.Analysis.(['Event',num2str(ii)]).Parent,fieldNameAnalysis,mResults.Analysis.(['Event',num2str(ii)]).(fieldNameAnalysis))
        end
        expMA(['Event',num2str(ii)],mPlots)
    end
    for ii = 1:length(fieldNamesResult)
        fieldNameResult = fieldNamesResult{ii};
        setappdata(mPlots.Result.Parent,fieldNameResult,mResults.Result.(fieldNameResult))
    end
    scrollbarCallback(mControls.Analysis.(eventTag).hScrollSlider,[],mAxes,mPlots,mControls,mParams)
    entryCode = 0; skipCalculation = 1;
    setappdata(mPlots.Analysis.(eventTag).Parent,'entryCode',entryCode)
    setappdata(mPlots.Result.Parent,'skipCalculation',skipCalculation)
    analyze(entryCode,eventTag,mAxes,mPlots,mControls,mParams)
elseif strcmp(actionName,'Save Data') == 1
    for ii = 1:validEventNum
        for jj = 1:length(fieldNamesAnalysis)
            fieldNameAnalysis = fieldNamesAnalysis{jj};
            mResults.Analysis.(['Event',num2str(ii)]).(fieldNameAnalysis) = getappdata(mPlots.Analysis.(['Event',num2str(ii)]).Parent,fieldNameAnalysis);
        end
    end
    for ii = 1:length(fieldNamesResult)
        fieldNameResult = fieldNamesResult{ii};
        mResults.Result.(fieldNameResult) = getappdata(mPlots.Result.Parent,fieldNameResult);
    end
    save(['.\Result\Subject' num2str(subjectIndex) 'Data.mat'],'mResults')
    export_fig(['.\Result\Subject' num2str(subjectIndex) 'Total.png'],mPlots.Result.Parent)
    fprintf(['Data Saved for Subject ' num2str(subjectIndex) ' from ' eventTag '!\n'])
%     PPGfingersig = getappdata(mPlots.Analysis.Event6.Parent,'PPGfingersig');
%     startIdx = getappdata(mPlots.Analysis.Event6.Parent,'startIdx');
%     timesig = getappdata(mPlots.Analysis.Event6.Parent,'timesig');
%     save('temp.mat','PPGfingersig','startIdx','timesig')
end