clear all;close all;clc

load .\Result\Subject100FullData

fieldNamesAnalysisLoad = {...
    'BPMaxLoc','BPMax','BPMinLoc','BPMin','ECGMaxLoc','ECGMax','ICGdzdtMaxLoc','ICGdzdtMax','ICGdzdtBPoint','ICGdzdtBPointLoc',...
    'BCGMaxLoc','BCGMax','BCGMinLoc','BCGMin','PPGfingerMaxLoc','PPGfingerMax','PPGfingerMinLoc','PPGfingerMin','PPGfingerFoot','PPGfingerFootLoc',...
    'PPGearMaxLoc','PPGearMax','PPGearMinLoc','PPGearMin','PPGearFoot','PPGearFootLoc',... 
    'PPGfeetMaxLoc','PPGfeetMax','PPGfeetMinLoc','PPGfeetMin','PPGfeetFoot','PPGfeetFootLoc',...
    'PPGtoeMaxLoc','PPGtoeMax','PPGtoeMinLoc','PPGtoeMin','PPGtoeFoot','PPGtoeFootLoc',...
    'PPGfingerECGWindow','PPGearECGWindow','PPGtoeECGWindow','PPGfeetECGWindow',...
    'PPGfingerICGWindow','PPGearICGWindow','PPGtoeICGWindow','PPGfeetICGWindow',...
    'PPGfingerBCGWindow','PPGearBCGWindow','PPGtoeBCGWindow','PPGfeetBCGWindow',...
    'PPGfingerECGBPInfo','PPGearECGBPInfo','PPGtoeECGBPInfo','PPGfeetECGBPInfo',...
    'PPGfingerICGBPInfo','PPGearICGBPInfo','PPGtoeICGBPInfo','PPGfeetICGBPInfo',...
    'PPGfingerBCGBPInfo','PPGearBCGBPInfo','PPGtoeBCGBPInfo','PPGfeetBCGBPInfo',...
    'IJWindow','IJBPInfo'};
fieldNamesResult = {'PAT','PTT','IJInfo','eventList','validEventNum','subjectIndex'};

for jj = 1:length(fieldNamesAnalysisLoad)
    fieldNameAnalysis = fieldNamesAnalysisLoad{jj};
    mResults.Analysis.(['Event',num2str(10)]).(fieldNameAnalysis) = mResults.Analysis.(['Event',num2str(15)]).(fieldNameAnalysis);
end
% PAT = mResults.Result.PAT;
% PAT
% for ii = 1:length(fieldNamesResult)
%     fieldNameResult = fieldNamesResult{ii};
%     setappdata(mPlots.Result.Parent,fieldNameResult,mResults.Result.(fieldNameResult))
% end
mResults.Analysis = rmfield(mResults.Analysis,{'Event11','Event12','Event13','Event14','Event15'});
save Subject100Data mResults